# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\"M\n\x15\x43reateEmployeeRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x13\n\x0bsecond_name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"$\n\x16\x43reateEmployeeResponse\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x12GetEmployeeRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"W\n\x13GetEmployeeResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x13\n\x0bsecond_name\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\"#\n\x15\x44\x65leteEmployeeRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"$\n\x16\x44\x65leteEmployeeResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xfe\x01\n\x0c\x45mployeesAPI\x12Q\n\x0e\x43reateEmployee\x12\x1e.example.CreateEmployeeRequest\x1a\x1f.example.CreateEmployeeResponse\x12H\n\x0bGetEmployee\x12\x1b.example.GetEmployeeRequest\x1a\x1c.example.GetEmployeeResponse\x12Q\n\x0e\x44\x65leteEmployee\x12\x1e.example.DeleteEmployeeRequest\x1a\x1f.example.DeleteEmployeeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CREATEEMPLOYEEREQUEST']._serialized_start=26
  _globals['_CREATEEMPLOYEEREQUEST']._serialized_end=103
  _globals['_CREATEEMPLOYEERESPONSE']._serialized_start=105
  _globals['_CREATEEMPLOYEERESPONSE']._serialized_end=141
  _globals['_GETEMPLOYEEREQUEST']._serialized_start=143
  _globals['_GETEMPLOYEEREQUEST']._serialized_end=175
  _globals['_GETEMPLOYEERESPONSE']._serialized_start=177
  _globals['_GETEMPLOYEERESPONSE']._serialized_end=264
  _globals['_DELETEEMPLOYEEREQUEST']._serialized_start=266
  _globals['_DELETEEMPLOYEEREQUEST']._serialized_end=301
  _globals['_DELETEEMPLOYEERESPONSE']._serialized_start=303
  _globals['_DELETEEMPLOYEERESPONSE']._serialized_end=339
  _globals['_EMPLOYEESAPI']._serialized_start=342
  _globals['_EMPLOYEESAPI']._serialized_end=596
# @@protoc_insertion_point(module_scope)
